#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
	GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL
